
import { Inter } from 'next/font/google'
import './globals.css'
import { ToastContainer } from 'react-toastify';
// import { AuthProvider } from '@/context/authcontext';
import { AuthProvider } from '@/context/AuthContext';
import { ProfileProvider } from '@/context/ProfilContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Test YouApp Awang Darmawan ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
   
    <html lang="en">
      <body className={inter.className}>
     <AuthProvider>
      <ProfileProvider>
        {children}
      <ToastContainer theme="colored" />
      </ProfileProvider>
      </AuthProvider>
        </body>
    </html>
   
  )
}

